import { StyleSheet } from 'react-native';
import { COLORS } from '../../constants';

export const getStyles = (theme) =>
  StyleSheet.create({
    address: {
      color: theme.text,
      fontSize: 14,
      fontWeight: 'bold',
      marginTop: 18,
    },
    addressContainer: {
      flex: 1,
      flexDirection: 'row',
      marginLeft: 20,
      marginRight: 20,
      maxHeight: 60,
    },
    categoriesContainer: {
      flex: 1,
      flexDirection: 'column',
      marginBottom: 20,
      marginLeft: 20,
      marginRight: 20,
      marginTop: 0,
    },
    column: {
      alignItems: 'center',
      flex: 1,
      justifyContent: 'center',
    },
    container: {
      alignItems: 'center',
      backgroundColor: theme.background,
      flex: 1,
    },
    copyIcon: {
      color: COLORS.primaryLight,
      fontSize: 24,
      marginLeft: 10,
      marginTop: 15,
      transform: [{ scaleX: -1 }],
    },
    cryptoAmount: {
      color: COLORS.black,
      fontSize: 18,
      fontWeight: 'bold',
      marginRight: 10,
    },
    cryptoItem: {
      alignItems: 'center',
      flexDirection: 'row',
      justifyContent: 'space-between',
      paddingBottom: 8,
      width: '100%',
    },
    cryptoName: {
      color: COLORS.black,
      fontSize: 18,
      fontWeight: 'light',
      margin: 16,
    },
    fiatConvertedAmount: {
      color: COLORS.black,
      fontSize: 36,
      fontWeight: 'bold',
      marginVertical: 50,
      textAlign: 'center',
    },
    fiatValue: {
      color: COLORS.primaryLight,
      fontSize: 14,
      fontWeight: 'bold',
    },
    leftContainer: {
      alignItems: 'flex-start',
      flexDirection: 'row',
    },
    listContainer: {
      backgroundColor: theme.background,
      flex: 1,
      marginBottom: 0,
      marginHorizontal: 8,
      paddingBottom: 32,
      paddingHorizontal: 16,
      paddingTop: 16,
    },
    logo: {
      fontSize: 24,
      fontWeight: 'bold',
      height: 81,
      marginLeft: 10,
      marginTop: 8,
      resizeMode: 'contain',
      textAlign: 'center',
      width: 81,
    },
    logoContainer: {
      alignItems: 'center',
      backgroundColor: COLORS.black,
      borderColor: COLORS.primary,
      flexDirection: 'row',
      justifyContent: 'center',
      marginBottom: 8,
      marginBottom: 16,
      width: '100%',
    },
    qrCode: {},
    qrCodeContainer: {
      alignItems: 'center',
      flexDirection: 'row',
      justifyContent: 'center',
      paddingVertical: 20,
      width: '100%',
    },
    rightContainer: {
      alignItems: 'flex-end',
    },
    row: {
      flex: 1,
      flexDirection: 'row',
      justifyContent: 'center',
    },
    screenTitle: {
      backgroundColor: theme.background,
      color: theme.text,
      fontFamily: 'Uto-Medium',
      fontSize: 20,
      marginBottom: 14,
      textAlign: 'left',
    },
    screenTitleContainer: {
      backgroundColor: theme.background,
      width: '100%',
    },
    scrollContainer: {
      borderRadius: 5,
      flex: 1,
      marginBottom: 36,
      marginLeft: 10,
      marginRight: 10,
      marginTop: 10,
    },
    sectionContainer: {
      backgroundColor: theme.background,
      flex: 1,
      marginTop: 32,
      paddingTop: 10,
      width: '98%',
    },
    sectionSubtitle: {
      color: theme.text,
      fontFamily: 'Uto-Regular',
      fontSize: 14,
      marginBottom: 20,
      marginLeft: 8,
      paddingTop: 10,
      textAlign: 'left',
    },
    sectionTitle: {
      color: theme.text,
      fontFamily: 'Uto-Bold',
      fontSize: 20,
      marginLeft: 8,
      marginTop: 20,
      paddingTop: 10,
      textAlign: 'left',
    },
    separator: {
      backgroundColor: COLORS.grey,
      height: 1,
      marginVertical: 8,
      width: '80%',
    },
    subtitleContainer: {
      width: '100%',
    },
    titleContainer: {
      alignItems: 'center',
    },
    warning: {
      color: theme.text,
      fontFamily: 'Uto-Light',
      fontSize: 12,
    },
    warningContainer: {
      alignItems: 'center',
      flex: 1,
      flexDirection: 'column',
      justifyContent: 'center',
      marginLeft: 20,
      marginRight: 20,
      maxHeight: 30,
    },
  });
