import { StyleSheet } from "react-native";
import { COLORS } from "../../constants";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.white,
    paddingTop: 20,
    alignItems: "center",
  },
  assetAmount: {
    fontSize: 36,
    fontWeight: "bold",
    color: COLORS.black,
    textAlign: "center",
    marginTop: 50,
    marginBottom: 6,
  },
  convertedAssetAmount: {
    fontSize: 12,
    color: COLORS.black,
    textAlign: "center",
  },
  input: {
    height: 40,
    marginTop: 10,
    color: COLORS.black,
    backgroundColor: COLORS.white,
    width: "80%",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
    border: 1,
    borderWidth: 1,
    borderColor: COLORS.greySecondary,
    borderRadius: 5,
    paddingVertical: 5,
    paddingHorizontal: 15,
  },
  button: {
    backgroundColor: COLORS.primaryLight,
    padding: 10,
    alignItems: "center",
    borderRadius: 5,
    width: "80%",
    marginTop: 122,
  },
  buttonText: {
    color: COLORS.black,
    fontSize: 16,
    fontWeight: "bold",
  },
  separator: {
    height: 1,
    backgroundColor: COLORS.grey,
    marginTop: 26,
    marginBottom: 8,
    width: "80%",
  },
  recentTransfersContainer: {
    width: "90%",
    backgroundColor: COLORS.greyDark,
    height: 300,
  },
  recentTransfersTitle: {
    fontSize: 16,
    fontWeight: "light",
    color: COLORS.black,
    textAlign: "left",
    marginVertical: 16,
    marginHorizontal: 20,
    backgroundColor: COLORS.greyDark,
  },
  labelContainer: {
    width: "90%",
  },
  label: {
    color: COLORS.black,
    fontSize: 16,
    textAlign: "left",
    marginTop: 16,
    marginBottom: 14,
    marginHorizontal: 20,
  },
  textContainer: {
    width: "90%",
  },
  text: {
    color: COLORS.greyLight,
    fontSize: 14,
    textAlign: "left",
    marginHorizontal: 20,
  },
  rowContainer: {
    width: "90%",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 4,
  },
});
