import { StyleSheet } from 'react-native';
import { COLORS } from '../../constants';

export const getStyles = (theme) =>
  StyleSheet.create({
    addToFavoritesBackgroundCircle: {
      backgroundColor: COLORS.greyBackground,
      borderRadius: 12,
    },
    addToFavoritesButton: {
      fontFamily: 'Uto-Medium',
      marginTop: 6,
    },
    addToFavoritesButton: {
      color: COLORS.primaryDark,
      fontFamily: 'Uto-Bold',
      marginRight: 4,
      marginTop: 6,
    },
    addToFavoritesButton: {
      fontFamily: 'Uto-Bold',
      marginLeft: 6,
      marginTop: 6,
    },
    addToFavoritesContainer: {
      flexDirection: 'row',
      marginLeft: 30,
      marginVertical: 10,
    },
    addToFavoritesIcon: {
      marginLeft: 1,
    },
    address: {
      fontFamily: 'Uto-Light',
    },
    addressAndNameContainer: {
      marginLeft: 8,
    },
    addressContainer: {
      flexDirection: 'row',
      marginLeft: 30,
      marginVertical: 10,
    },
    addressesContainer: {
      marginVertical: 20,
    },

    amount: {
      color: '#000',
      fontFamily: 'Uto-Bold',
      fontSize: 12,
    },
    assetAmount: {
      color: theme.text,
      fontFamily: 'Uto-Regular',
      fontSize: 52,
      textAlign: 'left',
    },
    assetAmountContainerTop: {
      alignItems: 'center',
      flexDirection: 'row',
      height: '50%',
    },
    assetBalance: {
      fontFamily: 'Uto-Regular',
      fontSize: 16,
      paddingTop: 4,
    },
    assetConversionContainer: {
      alignItems: 'center',
      flexDirection: 'row',
      height: 140,
      justifyContent: 'center',
      marginVertical: 20,
    },
    assetConversionContainerFirstColumn: {
      flex: 1,
      marginLeft: 20,
      width: '70%',
    },
    assetConversionContainerSecondColumn: {
      height: '85%',
      width: '30%',
    },
    assetName: {
      fontFamily: 'Uto-Medium',
      fontSize: 20,
    },
    assetSendSetup: {
      paddingLeft: 20,
      paddingTop: 20,
    },
    assetSendSetupColumn: {
      alignItems: 'center',
      backgroundColor: theme.input,
      borderRadius: 16,
      flexDirection: 'row',
      padding: 5,
    },
    assetSendSetupRow: {
      alignItems: 'center',
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginBottom: 8,
    },
    available: {
      color: '#666',
      fontFamily: 'Uto-Medium',
      fontSize: 12,
    },
    availableBalanceContainer: {
      backgroundColor: theme.input,
      borderRadius: 16,
      flexDirection: 'row',
      justifyContent: 'space-between',
      width: '100%',
    },
    availableBalanceContainer: {
      alignItems: 'center',
      justifyContent: 'space-between',
      padding: 10,
    },
    availableBalanceLeftContainer: {
      alignItems: 'center',
      flexDirection: 'column',
    },
    availableBalanceRightContainer: {
      alignItems: 'center',
      flexDirection: 'column',
    },
    availableBalanceText: {
      backgroundColor: theme.background,
      color: theme.text,
      fontFamily: 'Uto-Light',
      fontSize: 14,
      marginBottom: 20,
      textAlign: 'left',
    },
    balanceRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
    },
    button: {
      alignItems: 'center',
      backgroundColor: '#F48421',
      borderRadius: 5,
      marginTop: 20,
      padding: 10,
      width: '80%',
    },
    buttonContainer: {
      alignItems: 'center',
      height: 100,
      justifyContent: 'center',
      marginHorizontal: 16,
    },
    buttonText: {
      color: COLORS.white,
      fontFamily: 'Uto-Medium',
      fontSize: 16,
    },
    calculatedAssetAmount: {
      color: COLORS.greyLight,
      fontFamily: 'Uto-Medium',
      fontSize: 14,
      textAlign: 'left',
    },
    calculatedAssetAmountColumn: {
      alignItems: 'flex-start',
      flexDirection: 'row',
      height: 20,
      justifyContent: 'space-between',
    },
    calculatedAssetAmountContainer: {
      alignItems: 'flex-start',
      flexDirection: 'row',
      height: '50%',
      justifyContent: 'flex-end',
      marginRight: 45,
    },
    changeAssetIcon: {
      color: COLORS.primaryDark,
    },
    closeModal: {
      flexDirection: 'row',
      justifyContent: 'flex-end',
    },
    columnOne: {
      width: '70%',
    },
    columnTwo: {
      width: '30%',
    },
    contactsContainer: {
      width: '100%',
    },
    contactsTitleContainer: {
      flexDirection: 'row',
      justifyContent: 'space-between',
    },
    container: {
      backgroundColor: theme.background,
      flex: 1,
      justifyContent: 'space-between',
    },
    convertContainer: {
      borderBottomEndRadius: 16,
      borderBottomLeftRadius: 16,
      borderColor: '#E5E5E5',
      borderTopEndRadius: 16,
      borderTopLeftRadius: 16,
      borderWidth: 1,
      height: '80%',
      marginHorizontal: 20,
      marginTop: 16,
    },
    convertTitle: {
      color: COLORS.greyLight,
      fontFamily: 'Uto-Medium',
      fontSize: 14,
      marginLeft: 16,
      marginTop: 16,
    },
    dropdownIcon: {
      marginLeft: 4,
    },

    errorContainer: {
      backgroundColor: theme.background,
      height: 50,
      width: '90%',
    },
    errorText: {
      color: COLORS.error,
      fontFamily: 'Uto-Light',
      fontSize: 12,
      marginHorizontal: 4,
      paddingBottom: 30,
    },
    exampleAddressText: {
      color: COLORS.grey,
      fontFamily: 'Uto-Light',
      fontSize: 12,
      marginHorizontal: 28,
      paddingBottom: 30,
    },
    favoriteAddressName: {
      fontFamily: 'Uto-Medium',
    },
    favoritesTitle: {
      fontFamily: 'Uto-Bold',
      marginLeft: 30,
      textAlign: 'left',
    },
    feeContainer: {
      alignItems: 'center',
      flexDirection: 'row',
      height: 20,
      justifyContent: 'center',
    },
    feeText: {
      color: COLORS.primaryDark,
      fontFamily: 'Uto-Light',
      fontSize: 14,
      marginBottom: 16,
      textAlign: 'left',
    },
    feeTitle: {
      color: theme.text,
      fontFamily: 'Uto-Light',
      fontSize: 14,
      textAlign: 'center',
    },
    feeValue: {
      color: COLORS.primaryDark,
      fontFamily: 'Uto-Medium',
      fontSize: 14,
      marginLeft: 4,
      marginTop: 4,
      textAlign: 'center',
    },
    firstAssetContainer: {
      height: 200,
    },
    forwardIcon: {
      marginLeft: 8,
    },
    icon: {
      color: '#000',
      fontSize: 24,
      marginLeft: 4,
    },
    iconContainer: {
      alignItems: 'center',
      height: 40,
      justifyContent: 'center',
      marginHorizontal: 32,
      width: 40,
    },
    infoIcon: {
      marginLeft: 4,
    },
    input: {
      alignItems: 'center',
      backgroundColor: theme.input,
      borderRadius: 16,
      color: theme.text,
      flexDirection: 'row',
      fontFamily: 'Uto-Light',
      height: 50,
      justifyContent: 'flex-start',
      marginHorizontal: 24,

      marginTop: 10,
      paddingHorizontal: 15,
      paddingVertical: 5,
    },
    inputContainer: {
      alignItems: 'center',
      borderRadius: 5,
      borderWidth: 1,
      flexDirection: 'row',
    },
    inputContainer: {
      height: '50%',
      justifyContent: 'flex-end',
      marginTop: 8,
    },
    inputError: {
      alignItems: 'center',
      backgroundColor: theme.input,
      borderColor: COLORS.error,
      borderRadius: 16,
      color: theme.text,
      flexDirection: 'row',
      fontFamily: 'Uto-Light',
      height: 50,
      justifyContent: 'flex-start',
      marginHorizontal: 24,
      marginTop: 10,
      paddingHorizontal: 15,
      paddingVertical: 5,
    },
    line: {
      borderColor: '#E5E5E5',
      borderWidth: 1,
      flex: 1,
      height: 1,
    },
    mainContainer: {
      flex: 1,
    },
    maxButton: {
      alignItems: 'center',
      borderRadius: 5,
      justifyContent: 'center',
      marginTop: 20,
      paddingHorizontal: 20,
      paddingVertical: 5,
      width: 80,
    },
    maxButtonPressed: {
      alignItems: 'center',
      borderRadius: 5,
      justifyContent: 'center',
      marginTop: 20,
      paddingHorizontal: 20,
      paddingVertical: 5,
      width: 80,
    },
    maxButtonText: {
      color: theme.text,
      fontFamily: 'Uto-Medium',
      fontSize: 14,
    },
    maxButtonTextOnPressed: {
      color: theme.primaryLight,
      fontFamily: 'Uto-Medium',
      fontSize: 14,
    },
    messageContainer: {
      borderTopColor: COLORS.black,
      borderTopWidth: 1,
      height: '20%',
    },
    modal: {
      justifyContent: 'flex-end',
      margin: 0,
    },
    modalContent: {
      flexDirection: 'row',
      gap: 8,
      justifyContent: 'space-between',
      marginVertical: 16,
    },
    modalContentContainer: {
      backgroundColor: theme.background,
      backgroundColor: theme.background,
      borderTopLeftRadius: 16,
      borderTopRightRadius: 16,
      marginHorizontal: 8,
      padding: 32,
    },
    networkLabel: {
      color: COLORS.black,
      fontFamily: 'Uto-Regular',
      fontSize: 16,
      marginHorizontal: 6,
    },
    networkName: {
      color: COLORS.black,
      fontFamily: 'Uto-Bold',
      fontSize: 16,
    },
    pasteButton: {
      padding: 10,
    },
    pickerContainer: {
      backgroundColor: theme.input,
      borderRadius: 16,
      marginBottom: 20,
      width: '90%',
    },
    pickerItemNotNull: {
      color: COLORS.black,
      fontFamily: 'Uto-Medium',
      fontSize: 16,
      fontSize: 14,
    },
    pickerItemNull: {
      color: '#777C87',
      fontFamily: 'Uto-Medium',
      fontSize: 16,
      fontSize: 14,
    },
    pickerStyle: {
      color: theme.placeholder,
      fontFamily: 'Uto-Light',
      height: 50,
      width: '100%',
    },
    recentTransfersContainer: {
      backgroundColor: theme.background,
      height: 240,
      width: '90%',
    },
    recentTransfersTitle: {
      backgroundColor: theme.background,
      color: theme.text,
      fontFamily: 'Uto-Light',
      fontSize: 16,
      marginHorizontal: 8,
      marginVertical: 16,
      textAlign: 'left',
    },
    row: {
      flexDirection: 'row',
    },
    screenTitle: {
      backgroundColor: theme.background,
      color: theme.text,
      fontFamily: 'Uto-Medium',
      fontSize: 20,
      marginBottom: 10,
      marginHorizontal: 23,
      marginTop: 30,
      textAlign: 'left',
    },
    screenTitleContainer: {
      backgroundColor: theme.background,
      width: '100%',
    },
    secondAssetContainer: {
      height: 200,
    },
    sectionSubtitle: {
      color: theme.text,
      fontFamily: 'Uto-Regular',
      fontSize: 14,
      marginBottom: 20,
      marginLeft: 8,
      paddingTop: 10,
      textAlign: 'left',
    },
    sectionTitle: {
      color: theme.text,
      fontFamily: 'Uto-Bold',
      fontSize: 20,
      marginLeft: 8,
      marginTop: 20,
      paddingTop: 10,
      textAlign: 'left',
    },
    selectAsset: {
      alignItems: 'center',
      backgroundColor: theme.input,
      borderRadius: 16,
      flexDirection: 'row',
      height: 50,
      justifyContent: 'space-between',
      marginLeft: 16,
      paddingRight: 8,
      width: 160,
    },
    selectedAsetSymbol: {
      color: COLORS.greyLight,
      fontFamily: 'Uto-Regular',
      marginLeft: 2,
    },
    selectedAssetImage: {
      height: 30,
      marginLeft: 8,
      width: 30,
    },
    selectedAssetImageContainer: {
      alignItems: 'center',
      backgroundColor: theme.input,
      borderRadius: 16,
      flexDirection: 'row',
      height: 55,
      marginLeft: 20,
      marginTop: 28,
      width: 65,
    },
    selectedAssetSymbol: {
      color: COLORS.greyLight,
      fontFamily: 'Uto-Medium',
      marginHorizontal: 8,
      marginTop: 8,
      textAlign: 'center',
    },
    separator: {
      backgroundColor: 'black',
      height: 20,
      marginLeft: 26,
      width: 2,
    },
    showAllButton: {
      color: COLORS.primaryDark,
      fontFamily: 'Uto-Bold',
      marginRight: 30,
    },
    subtitleContainer: {
      alignItems: 'flex-start',
    },
    swapLineContainer: {
      alignItems: 'center',
      flexDirection: 'row',
      width: '100%',
    },
    symbol: {
      fontFamily: 'Uto-Bold',
      fontSize: 12,
      marginLeft: 2,
    },
    textInput: {
      color: COLORS.greyLight,
      fontFamily: 'Uto-Medium',
      fontSize: 40,
      height: '100%',
      marginRight: 20,
      paddingBottom: 32,
      textAlign: 'right',
    },
    titleContainer: {
      alignItems: 'flex-start',
    },
    toAddress: {
      fontFamily: 'Uto-Light',
    },
    toTitle: {
      fontFamily: 'Uto-Medium',
    },
    totalText: {
      color: theme.text,
      fontFamily: 'Uto-Light',
      fontSize: 14,
      textAlign: 'left',
    },
    validText: {
      color: COLORS.green,
      fontFamily: 'Uto-Light',
      fontSize: 12,
      marginHorizontal: 4,
      paddingBottom: 30,
    },
    validationContainer: {
      alignItems: 'center',
      flexDirection: 'row',
    },
    verifiedIcon: {
      marginBottom: 28,
      paddingLeft: 24,
    },
    walletIconContainer: {
      alignItems: 'center',
      backgroundColor: theme.input,
      borderRadius: 15,
      flexDirection: 'row',
      height: 30,
      justifyContent: 'center',
      marginLeft: 12,
      marginRight: 6,
      marginTop: 4,
      paddingLeft: 2,
      width: 30,
    },
    walletRow: {
      flexDirection: 'row',
      marginTop: 8,
    },
    withdrawFeeContainer: {
      alignItems: 'center',
      flexDirection: 'row',
      height: 20,
      justifyContent: 'center',
    },
  });
