export const assetsTypes = {
  SELECT_ASSET: "SELECT_ASSET",
  UPDATE_ASSETS_PRICES: "UPDATE_ASSETS_PRICES",
  UPDATE_BALANCES: "UPDATE_BALANCES",
  GET_ASSETS_LITTLE_LINE_CHARTS: "GET_ASSETS_LITTLE_LINE_CHARTS",
  GET_CANDLESTICK_CHART: "GET_CANDLESTICK_CHART",
  GET_STORED_PRICES: "GET_STORED_PRICES",
};
