export const assetsTypes = {
  SELECT_ASSET: "SELECT_ASSET",
  UPDATE_ASSETS_PRICES: "UPDATE_ASSETS_PRICES",
  UPDATE_BALANCES: "UPDATE_BALANCES",
  GET_ASSETS_LITTLE_LINE_CHARTS: "GET_ASSETS_LITTLE_LINE_CHARTS",
  GET_CANDLESTICK_CHART_REQUEST: "GET_CANDLESTICK_CHART_REQUEST",
  GET_CANDLESTICK_CHART_SUCCESS: "GET_CANDLESTICK_CHART_SUCCESS",
  GET_CANDLESTICK_CHART_FAILURE: "GET_CANDLESTICK_CHART_FAILURE",
  GET_STORED_PRICES: "GET_STORED_PRICES",
  GET_HISTORY: "GET_HISTORY",
};
