export const assetsTypes = {
  SELECT_ASSET: "SELECT_ASSET",
  UPDATE_ASSETS_PRICES: "UPDATE_ASSETS_PRICES",
  GET_ASSETS_LITTLE_LINE_CHARTS: "GET_ASSETS_LITTLE_LINE_CHARTS",
  GET_STORED_PRICES: "GET_STORED_PRICES",
};
