export const authTypes = {
  SIGN_UP_REQUEST: "SIGN_UP_REQUEST",
  SIGN_UP_SUCCESS: "SIGN_UP_SUCCESS",
  SIGN_UP_FAILURE: "SIGN_UP_FAILURE",
  SIGN_IN_REQUEST: "SIGN_IN_REQUEST",
  SIGN_IN_SUCCESS: "SIGN_IN_SUCCESS",
  SIGN_IN_FAILURE: "SIGN_IN_FAILURE",
  VERIFICATION_TOKEN_REQUEST: "VERIFICATION_TOKEN_REQUEST",
  VERIFICATION_TOKEN_SUCCESS: "VERIFICATION_TOKEN_SUCCESS",
  VERIFICATION_TOKEN_FAILURE: "VERIFICATION_TOKEN_FAILURE",
  CLEAR_ERROR: "CLEAR_ERROR",
};
