export const blockchainsTypes = {
  FETCH_BLOCKCHAINS_REQUEST: "FETCH_BLOCKCHAINS_REQUEST",
  FETCH_BLOCKCHAINS_SUCCESS: "FETCH_BLOCKCHAINS_SUCCESS",
  FETCH_BLOCKCHAINS_FAILURE: "FETCH_BLOCKCHAINS_FAILURE",
};
