export const userTypes = {
  GET_USER_INFO_BY_ID: 'GET_USER_INFO_BY_ID',
  ADD_USER: 'ADD_USER',
  SET_USER_IMAGE: 'SET_USER_IMAGE',
  SEND_EMAIL: 'SEND_EMAIL',
  SEND_SMS: 'SEND_SMS',
  SET_SELECTED_ADDRESS: 'SET_SELECTED_ADDRESS',
  SET_FAVORITE_ADDRESS: 'SET_FAVORITE_ADDRESS',
  FAVORITE_ADDRESS_SAVED_SUCCESSFULLY: 'FAVORITE_ADDRESS_SAVED_SUCCESSFULLY',
  FAVORITE_ADDRESS_SAVE_FAILED: 'FAVORITE_ADDRESS_SAVE_FAILED',
};
