import { StyleSheet } from "react-native";
import { COLORS } from "../../constants";

export const getStyles = (theme) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: theme.background,
      paddingTop: 20,
      alignItems: "center",
    },
    contactsContainer: {
      width: "100%",
    },
    contactsTitleContainer: {
      flexDirection: "row",
      justifyContent: "space-between",
    },
    favoritesTitle: {
      textAlign: "left",
      marginLeft: 30,
      fontFamily: "Uto-Bold",
    },
    addressesContainer: {
      marginVertical: 20,
    },
    addressContainer: {
      flexDirection: "row",
      marginLeft: 30,
      marginVertical: 10,
    },
    address: {
      fontFamily: "Uto-Light",
    },
    favoriteAddressName: {
      fontFamily: "Uto-Medium",
    },
    addToFavoriteIcon: {},
    addToFavoriteButton: {
      fontFamily: "Uto-Medium",
      marginTop: 6,
    },

    addToFavoritesContainer: {
      flexDirection: "row",
      marginLeft: 30,
      marginVertical: 10,
    },
    addToFavoritesButton: {
      fontFamily: "Uto-Bold",
      color: COLORS.primaryDark,
      marginRight: 30,
    },
    assetConversionContainer: {
      flexDirection: "row",
      justifyContent: "center",
      alignItems: "center",
      height: 140,
      marginVertical: 20,
    },
    assetAmountContainerTop: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "flex-end",
      height: "50%",
    },
    assetAmount: {
      fontSize: 52,
      fontFamily: "Uto-Light",
      color: theme.text,
      width: "100%",
      textAlign: "right",
    },
    selectedAssetSymbol: {
      fontSize: 16,
      fontFamily: "Uto-Medium",
      color: COLORS.greyLight,
      textAlign: "center",
      marginHorizontal: 8,
      marginTop: 8,
    },
    calculatedAssetAmountContainer: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "flex-end",
      paddingLeft: 20,
      height: "50%",
    },
    calculatedAssetAmountColumn: {
      flexDirection: "column",
      alignItems: "center",
      justifyContent: "center",
      height: 20,
    },
    calculatedAssetAmount: {
      fontSize: 14,
      fontFamily: "Uto-Medium",
      color: COLORS.primaryDark,
      textAlign: "center",
    },
    withdrawFeeContainer: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      height: 20,
    },
    changeAssetIcon: {
      color: COLORS.primaryDark,
    },
    feeContainer: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      height: 20,
    },
    feeTitle: {
      fontSize: 14,
      fontFamily: "Uto-Light",
      color: theme.text,
      textAlign: "center",
    },
    feeValue: {
      fontSize: 14,
      fontFamily: "Uto-Medium",
      color: COLORS.primaryDark,
      textAlign: "center",
      marginTop: 4,
      marginLeft: 4,
    },
    selectedAssetImageContainer: {
      width: 65,
      height: 55,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: COLORS.greyLight,
      backgroundColor: theme.background,
      marginLeft: 20,
      flexDirection: "row",
      alignItems: "center",
    },
    selectedAssetImage: {
      width: 30,
      height: 30,
      marginLeft: 8,
    },
    input: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "flex-start",
      backgroundColor: theme.input,
      borderRadius: 16,
      paddingVertical: 5,
      paddingHorizontal: 15,
      width: "90%",
      height: 50,
      color: theme.text,
      fontFamily: "Uto-Light",
    },
    button: {
      backgroundColor: COLORS.primaryLight,
      padding: 10,
      alignItems: "center",
      borderRadius: 5,
      width: "80%",
      marginTop: 11,
    },
    buttonText: {
      color: COLORS.black,
      fontSize: 16,
      fontFamily: "Uto-Medium",
    },
    separator: {
      height: 1,
      backgroundColor: theme.disabled,
      marginBottom: 8,
      marginHorizontal: 20,
      width: "100%",
    },
    recentTransfersContainer: {
      width: "90%",
      backgroundColor: theme.background,
      height: 240,
    },
    recentTransfersTitle: {
      fontSize: 16,
      fontFamily: "Uto-Light",
      color: theme.text,
      textAlign: "left",
      marginVertical: 16,
      marginHorizontal: 8,
      backgroundColor: theme.background,
    },
    screenTitleContainer: {
      width: "100%",
      backgroundColor: theme.background,
    },
    screenTitle: {
      fontSize: 20,
      color: theme.text,
      textAlign: "left",
      marginHorizontal: 23,
      marginTop: 30,
      marginBottom: 20,
      backgroundColor: theme.background,
      fontFamily: "Uto-Medium",
    },
    exampleAddressText: {
      fontFamily: "Uto-Light",
      fontSize: 12,
      color: COLORS.grey,
      paddingBottom: 30,
    },
    maxButton: {
      backgroundColor: COLORS.greyLight,
      paddingHorizontal: 20,
      paddingVertical: 5,
      borderRadius: 5,
      marginLeft: 12,
      justifyContent: "center",
      alignItems: "center",
      marginTop: 26,
      width: 80,
    },

    maxButtonPressed: {
      backgroundColor: COLORS.primary,
      paddingHorizontal: 20,
      paddingVertical: 5,
      borderRadius: 5,
      marginLeft: 12,
      justifyContent: "center",
      alignItems: "center",
      marginTop: 26,
      width: 80,
    },
    maxButtonText: {
      color: COLORS.white,
      fontSize: 14,
      fontFamily: "Uto-Medium",
    },
    pickerContainer: {
      borderRadius: 16,
      marginBottom: 20,
      width: "90%",
      backgroundColor: theme.input,
    },
    pickerStyle: {
      width: "100%",
      height: 50,
      color: theme.placeholder,
      fontFamily: "Uto-Light",
    },
    pickerItemNull: {
      fontSize: 16,
      color: "#777C87",
      fontFamily: "Uto-Medium",
      fontSize: 14,
    },
    pickerItemNotNull: {
      fontSize: 16,
      color: COLORS.black,
      fontFamily: "Uto-Medium",
      fontSize: 14,
    },
    errorContainer: {
      width: "90%",
      backgroundColor: theme.background,
      height: 50,
    },
    errorText: {
      color: COLORS.error,
      fontSize: 14,
      fontFamily: "Uto-Medium",
      textAlign: "center",
    },

    assetConversionContainerFirstColumn: {
      flex: 1,
      width: "70%",
      marginLeft: 20,
    },
    assetConversionContainerSecondColumn: {
      width: "30%",
      height: "85%",
    },
    availableBalanceContainer: {
      width: "100%",
      backgroundColor: theme.background,
      paddingHorizontal: 72,
      marginBottom: 20,
      justifyContent: "space-between",
      flexDirection: "row",
    },
    availableBalanceLeftContainer: {
      flexDirection: "column",
      alignItems: "center",
    },
    availableBalanceRightContainer: {
      flexDirection: "column",
      alignItems: "center",
    },
    availableBalanceText: {
      fontSize: 14,
      color: theme.text,
      textAlign: "left",
      marginBottom: 20,
      backgroundColor: theme.background,
      fontFamily: "Uto-Light",
    },
    feeText: {
      fontSize: 14,
      color: COLORS.primaryDark,
      textAlign: "left",
      marginBottom: 16,
      fontFamily: "Uto-Light",
    },
    totalText: {
      fontSize: 14,
      color: theme.text,
      textAlign: "left",
      fontFamily: "Uto-Light",
    },
  });
