import { StyleSheet } from "react-native";
import { COLORS } from "../../constants";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.white,
    paddingTop: 20,
    alignItems: "center",
  },
  assetAmount: {
    fontSize: 36,
    fontWeight: "bold",
    color: COLORS.black,
    textAlign: "center",
    marginVertical: 50,
  },
  input: {
    height: 40,
    marginTop: 10,
    color: COLORS.black,
    backgroundColor: COLORS.white,
    width: "80%",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
    borderWidth: 1,
    borderColor: COLORS.greySecondary,
    borderRadius: 5,
    paddingVertical: 5,
    paddingHorizontal: 15,
  },
  button: {
    backgroundColor: COLORS.primaryLight,
    padding: 10,
    alignItems: "center",
    borderRadius: 5,
    width: "80%",
    marginTop: 11,
  },
  buttonText: {
    color: COLORS.black,
    fontSize: 16,
    fontWeight: "bold",
  },
  separator: {
    height: 1,
    backgroundColor: COLORS.grey,
    marginTop: 16,
    marginBottom: 8,
    width: "80%",
  },
  recentTransfersContainer: {
    width: "90%",
    backgroundColor: COLORS.white,
    height: 240,
  },
  recentTransfersTitle: {
    fontSize: 16,
    fontFamily: "Uto-Light",
    color: COLORS.black,
    textAlign: "left",
    marginVertical: 16,
    marginHorizontal: 20,
    backgroundColor: COLORS.white,
  },
  screenTitleContainer: {
    width: "100%",
    backgroundColor: COLORS.white,
  },
  screenTitle: {
    fontSize: 20,
    color: COLORS.black,
    textAlign: "left",
    marginHorizontal: 46,
    marginTop: 50,
    marginBottom: 14,
    backgroundColor: COLORS.white,
    fontFamily: "Uto-Medium",
  },
});
