import { StyleSheet } from 'react-native';
import { COLORS } from '../../constants';

export const getStyles = (theme) =>
  StyleSheet.create({
    addToFavoritesBackgroundCircle: {
      backgroundColor: COLORS.greyBackground,
      borderRadius: 12,
    },
    addToFavoritesButton: {
      fontFamily: 'Uto-Medium',
      marginTop: 6,
    },
    addToFavoritesButton: {
      color: COLORS.primaryDark,
      fontFamily: 'Uto-Bold',
      marginRight: 4,
      marginTop: 6,
    },
    addToFavoritesButton: {
      fontFamily: 'Uto-Bold',

      marginLeft: 6,
      marginTop: 3,
    },
    addToFavoritesContainer: {
      flexDirection: 'row',
      marginLeft: 30,
      marginVertical: 10,
    },
    addToFavoritesIcon: {
      marginLeft: 1,
    },
    address: {
      fontFamily: 'Uto-Light',
    },
    addressAndNameContainer: {
      marginLeft: 8,
    },
    addressContainer: {
      flexDirection: 'row',
      marginLeft: 30,
      marginVertical: 10,
    },
    addressesContainer: {
      marginVertical: 20,
    },
    assetAmount: {
      color: theme.text,
      fontFamily: 'Uto-Light',
      fontSize: 52,
      textAlign: 'right',
      width: '100%',
    },

    assetAmountContainerTop: {
      alignItems: 'center',
      flexDirection: 'row',
      height: '50%',
      justifyContent: 'flex-end',
    },
    assetConversionContainer: {
      alignItems: 'center',
      flexDirection: 'row',
      height: 140,
      justifyContent: 'center',
      marginVertical: 20,
    },
    assetConversionContainerFirstColumn: {
      flex: 1,
      marginLeft: 20,
      width: '70%',
    },
    assetConversionContainerSecondColumn: {
      height: '85%',
      width: '30%',
    },
    availableBalanceContainer: {
      backgroundColor: theme.background,
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginBottom: 20,
      paddingHorizontal: 72,
      width: '100%',
    },
    availableBalanceLeftContainer: {
      alignItems: 'center',
      flexDirection: 'column',
    },
    availableBalanceRightContainer: {
      alignItems: 'center',
      flexDirection: 'column',
    },
    availableBalanceText: {
      backgroundColor: theme.background,
      color: theme.text,
      fontFamily: 'Uto-Light',
      fontSize: 14,
      marginBottom: 20,
      textAlign: 'left',
    },
    button: {
      alignItems: 'center',
      backgroundColor: '#F48421',
      borderRadius: 5,
      padding: 10,
      width: '80%',
    },
    buttonContainer: {
      alignItems: 'center',
      borderColor: '#E5E5E5',
      borderWidth: 1,

      justifyContent: 'center',
      padding: 10,
    },
    buttonText: {
      color: COLORS.white,
      fontFamily: 'Uto-Medium',
      fontSize: 16,
    },
    calculatedAssetAmount: {
      color: COLORS.primaryDark,
      fontFamily: 'Uto-Medium',
      fontSize: 14,
      textAlign: 'center',
    },
    calculatedAssetAmountColumn: {
      alignItems: 'center',
      flexDirection: 'column',
      height: 20,
      justifyContent: 'center',
    },
    calculatedAssetAmountContainer: {
      alignItems: 'center',
      flexDirection: 'row',
      height: '50%',
      justifyContent: 'flex-end',
      paddingLeft: 20,
    },
    changeAssetIcon: {
      color: COLORS.primaryDark,
    },
    contactsContainer: {
      width: '100%',
    },
    contactsTitleContainer: {
      flexDirection: 'row',
      justifyContent: 'space-between',
    },
    container: {
      backgroundColor: theme.background,
      flex: 1,
      justifyContent: 'space-between', // Alinea el contenido al principio y el botón al final.
    },
    errorContainer: {
      backgroundColor: theme.background,
      height: 50,
      width: '90%',
    },
    errorText: {
      color: COLORS.error,
      fontFamily: 'Uto-Light',
      fontSize: 12,
      marginHorizontal: 4,
      paddingBottom: 30,
    },
    exampleAddressText: {
      color: COLORS.grey,
      fontFamily: 'Uto-Light',
      fontSize: 11,
      marginHorizontal: 28,
      marginTop: 4,
      paddingBottom: 30,
    },
    favoriteAddressName: {
      fontFamily: 'Uto-Medium',
    },
    favoritesTitle: {
      fontFamily: 'Uto-Bold',
      marginLeft: 30,
      textAlign: 'left',
    },
    feeContainer: {
      alignItems: 'center',
      flexDirection: 'row',
      height: 20,
      justifyContent: 'center',
    },
    feeText: {
      color: COLORS.primaryDark,
      fontFamily: 'Uto-Light',
      fontSize: 14,
      marginBottom: 16,
      textAlign: 'left',
    },
    feeTitle: {
      color: theme.text,
      fontFamily: 'Uto-Light',
      fontSize: 14,
      textAlign: 'center',
    },
    feeValue: {
      color: COLORS.primaryDark,
      fontFamily: 'Uto-Medium',
      fontSize: 14,
      marginLeft: 4,
      marginTop: 4,
      textAlign: 'center',
    },
    input: {
      alignItems: 'center',
      backgroundColor: theme.input,
      borderRadius: 16,
      color: theme.text,
      flexDirection: 'row',
      fontFamily: 'Uto-Light',
      height: 50,
      justifyContent: 'flex-start',
      marginHorizontal: 24,

      marginTop: 10,
      paddingHorizontal: 15,
      paddingVertical: 5,
    },
    inputContainer: {
      alignItems: 'center',
      borderRadius: 5,
      borderWidth: 1,
      flexDirection: 'row',
    },
    inputError: {
      alignItems: 'center',
      backgroundColor: theme.input,
      borderColor: COLORS.error,
      borderRadius: 16,
      color: theme.text,
      flexDirection: 'row',
      fontFamily: 'Uto-Light',
      height: 50,
      justifyContent: 'flex-start',
      marginHorizontal: 24,
      marginTop: 10,
      paddingHorizontal: 15,
      paddingVertical: 5,
    },
    mainContainer: {
      flex: 1,
    },
    maxButton: {
      alignItems: 'center',
      backgroundColor: COLORS.greyLight,
      borderRadius: 5,
      justifyContent: 'center',
      marginLeft: 12,
      marginTop: 26,
      paddingHorizontal: 20,
      paddingVertical: 5,
      width: 80,
    },
    maxButtonPressed: {
      alignItems: 'center',
      backgroundColor: COLORS.primary,
      borderRadius: 5,
      justifyContent: 'center',
      marginLeft: 12,
      marginTop: 26,
      paddingHorizontal: 20,
      paddingVertical: 5,
      width: 80,
    },
    maxButtonText: {
      color: COLORS.white,
      fontFamily: 'Uto-Medium',
      fontSize: 14,
    },

    pasteButton: {
      padding: 10,
    },
    pickerContainer: {
      backgroundColor: theme.input,
      borderRadius: 16,
      marginBottom: 20,
      width: '90%',
    },
    pickerItemNotNull: {
      color: COLORS.black,
      fontFamily: 'Uto-Medium',
      fontSize: 16,
      fontSize: 14,
    },
    pickerItemNull: {
      color: '#777C87',
      fontFamily: 'Uto-Medium',
      fontSize: 16,
      fontSize: 14,
    },
    pickerStyle: {
      color: theme.placeholder,
      fontFamily: 'Uto-Light',
      height: 50,
      width: '100%',
    },
    recentTransfersContainer: {
      backgroundColor: theme.background,
      height: 240,
      width: '90%',
    },
    recentTransfersTitle: {
      backgroundColor: theme.background,
      color: theme.text,
      fontFamily: 'Uto-Light',
      fontSize: 16,
      marginHorizontal: 8,
      marginVertical: 16,
      textAlign: 'left',
    },
    screenTitle: {
      backgroundColor: theme.background,
      color: theme.text,
      fontFamily: 'Uto-Medium',
      fontSize: 20,
      marginBottom: 10,
      marginHorizontal: 23,
      marginTop: 30,
      textAlign: 'left',
    },
    screenTitleContainer: {
      backgroundColor: theme.background,
      width: '100%',
    },
    scrollContainer: {
      flex: 1,
    },
    sectionSubtitle: {
      color: theme.text,
      fontFamily: 'Uto-Regular',
      fontSize: 14,
      marginBottom: 20,
      marginLeft: 8,
      paddingTop: 10,
      textAlign: 'left',
    },
    sectionTitle: {
      color: theme.text,
      fontFamily: 'Uto-Bold',
      fontSize: 20,
      marginLeft: 8,
      marginTop: 20,
      paddingTop: 10,
      textAlign: 'left',
    },
    selectedAssetImage: {
      height: 30,
      marginLeft: 8,
      width: 30,
    },
    selectedAssetImageContainer: {
      alignItems: 'center',
      backgroundColor: theme.background,
      borderColor: COLORS.greyLight,
      borderRadius: 16,
      borderWidth: 1,
      flexDirection: 'row',
      height: 55,
      marginLeft: 20,
      width: 65,
    },
    selectedAssetSymbol: {
      color: COLORS.greyLight,
      fontFamily: 'Uto-Medium',
      fontSize: 16,
      marginHorizontal: 8,
      marginTop: 8,
      textAlign: 'center',
    },
    separator: {
      backgroundColor: theme.disabled,
      height: 1,
      marginBottom: 8,
      marginHorizontal: 20,
      width: '100%',
    },
    showAllButton: {
      color: COLORS.primaryDark,
      fontFamily: 'Uto-Bold',
      marginRight: 30,
    },
    subtitleContainer: {
      alignItems: 'flex-start',
    },
    titleContainer: {
      alignItems: 'flex-start',
    },
    totalText: {
      color: theme.text,
      fontFamily: 'Uto-Light',
      fontSize: 14,
      textAlign: 'left',
    },
    validText: {
      color: COLORS.green,
      fontFamily: 'Uto-Light',
      fontSize: 12,
      marginHorizontal: 4,
      paddingBottom: 30,
    },
    validationContainer: {
      alignItems: 'center',
      flexDirection: 'row',
    },
    verifiedIcon: {
      marginBottom: 28,
      paddingLeft: 24,
    },
    withdrawFeeContainer: {
      alignItems: 'center',
      flexDirection: 'row',
      height: 20,
      justifyContent: 'center',
    },
  });
