import { StyleSheet, Platform } from 'react-native';
import { COLORS } from '../../constants';

export const getStyles = (theme) =>
  StyleSheet.create({
    amount: {
      color: COLORS.black,
      fontFamily: 'Uto-Light',
      fontSize: 16,
      marginVertical: 0,
    },
    amountRow: {
      alignItems: 'baseline',
      flexDirection: 'row',
    },
    amountStyle: {
      color: COLORS.black,
      fontFamily: 'Uto-Light',
      fontSize: 24,
      marginRight: 4,
    },
    balanceDetails: {
      alignItems: 'center',
      backgroundColor: theme.background,
      flexDirection: 'row',
      height: 80,
    },
    balanceTitle: {
      color: COLORS.greyLight,
      fontFamily: 'Uto-Medium',
      fontSize: 12,
      marginTop: 20,
      paddingTop: 10,
      textAlign: 'left',
    },
    calculatedBalance: {
      fontFamily: 'Uto-Light',
      fontSize: 12,
    },
    categoriesContainer: {
      flex: 1,
      flexDirection: 'column',
      marginBottom: 20,
      marginLeft: 20,
      marginRight: 20,
      marginTop: 0,
    },
    categoryImage: {
      height: 55,
      marginLeft: 8,
      resizeMode: 'contain',
      width: 55,
    },
    column: {
      alignItems: 'center',
      flex: 1,
      justifyContent: 'center',
    },
    container: {
      alignItems: 'center',
      backgroundColor: theme.background,
      flex: 1,
      paddingTop: 20,
      position: 'relative',
    },
    cryptoSymbol: {
      color: COLORS.greyDark,
      fontFamily: 'Uto-Light',
      fontSize: 12,
      marginHorizontal: 16,
      marginTop: 2,
      textTransform: 'uppercase',
    },
    fiatConvertedAmount: {
      color: COLORS.black,
      fontFamily: 'Uto-Medium',
      fontSize: 52,
      marginTop: 0,
      paddingBottom: 10,
      textAlign: 'center',
    },
    fiatSymbol: {
      bottom: 10,
      color: COLORS.black,
      fontFamily: 'Uto-Light',
      fontSize: 60,
      textAlign: 'center',
    },
    fiatTicker: {
      color: COLORS.greyLight,
      fontFamily: 'Uto-Medium',
      fontSize: 12,
      right: 8,
      textAlign: 'center',
      top: 8,
    },
    fiatValue: {
      color: COLORS.primaryLight,
      fontFamily: 'Uto-Bold',
      fontSize: 14,
    },
    language: {
      color: theme.text,
      fontFamily: 'Uto-Light',
      fontSize: 14,
      marginBottom: 8,
    },
    leftContainer: {
      alignItems: 'flex-start',
      flexDirection: 'row',
    },
    listContainer: {
      backgroundColor: theme.background,
      flex: 1,
      marginBottom: 0,
      marginHorizontal: 8,
      paddingBottom: 32,
      paddingHorizontal: 16,
      paddingTop: 16,
    },

    listScrolLView: {
      flex: 1,
      marginLeft: 32,
      marginRight: 10,
    },
    localCurrency: {
      color: theme.text,
      fontFamily: 'Uto-Light',
      fontSize: 14,
      marginBottom: 8,
    },
    logo: {
      height: 40,
      marginTop: 8,
      resizeMode: 'contain',
      width: 40,
    },
    middleContainer: {
      alignItems: 'center',
      flexDirection: 'row',
      flex: 1,
      justifyContent: 'center',
    },
    optionItem: {
      alignItems: 'center',
      flexDirection: 'row',
      height: 50,
      justifyContent: 'space-between',
      paddingBottom: 8,
      width: '100%',
    },
    optionText: {
      color: theme.text,
      fontFamily: 'Uto-Medium',
      fontSize: 16,
      marginHorizontal: 16,
    },
    percentageStyle: {
      color: COLORS.interest,
      fontFamily: 'Uto-Light',
      fontSize: 12,
      marginRight: 4,
    },
    priceFiatAmount: {
      color: COLORS.black,
      fontFamily: 'Uto-Light',
      fontSize: 16,
      marginRight: 1,
      marginTop: 10,
    },
    rightContainer: {
      alignItems: 'flex-end',
      flexDirection: 'column',
    },
    row: {
      alignItems: 'center',
      flex: 1,
      flexDirection: 'row',
      justifyContent: 'center',
    },
    scrollContainer: {
      borderRadius: 5,
      flex: 1,
      marginBottom: 36,
      marginLeft: 10,
      marginRight: 10,
      marginTop: 10,
    },
    scrollIndicator: {
      backgroundColor: 'rgba(227, 128, 44, 0.5)',
      borderRadius: 3,
      bottom: 0,
      marginLeft: 4,
      position: 'absolute',
      right: 0,
      top: 0,
      width: 6,
    },
    scrollView: {
      flex: 1,
    },
    sectionComponent: {
      alignItems: 'center',
      backgroundColor: theme.background,
      borderRadius: 16,
      flex: 1,
      flexDirection: 'row',
      height: 90,
      justifyContent: 'space-between',
      marginHorizontal: 12,
      marginTop: 28,
      maxHeight: 90,
      paddingTop: 10,
      padding: 10,
      ...Platform.select({
        ios: {
          shadowColor: theme.text,
          shadowOffset: { width: 10, height: 10 },
          shadowOpacity: 0.5,
          shadowRadius: 5,
        },
        android: {
          elevation: 10,
        },
      }),
    },
    sectionContainer: {
      backgroundColor: theme.background,
      flex: 1,
      marginTop: 16,
      width: '98%',
    },
    sectionSubtitle: {
      color: theme.text,
      fontFamily: 'Uto-Regular',
      fontSize: 16,
      marginBottom: 20,
      marginLeft: 8,
      paddingTop: 10,
      textAlign: 'left',
    },
    sectionTitle: {
      color: theme.text,
      fontFamily: 'Uto-Bold',
      fontSize: 20,
      marginLeft: 8,
      marginTop: 20,
      paddingTop: 10,
      textAlign: 'left',
    },
    sectionTitleTimeframe: {
      color: COLORS.grey,
      fontFamily: 'Uto-Light',
      fontSize: 12,
      marginLeft: 6,
      marginTop: 26,
      paddingTop: 6,
      textAlign: 'left',
    },
    separator: {
      backgroundColor: '#ddd',
      height: 1,
      marginVertical: 8,
    },
    subtitleContainer: {
      alignItems: 'flex-start',
      flexDirection: 'row',
    },
    textContainer: {
      alignItems: 'flex-start',
      flexDirection: 'column',
    },
    titleContainer: {
      alignItems: 'flex-start',
    },
    titleStyle: {
      color: theme.text,
      fontFamily: 'Uto-Medium',
      fontSize: 24,
      marginHorizontal: 8,
      marginVertical: 16,
      textAlign: 'left',
    },
    unverifiedIcon: {
      marginLeft: 8,
    },
    verifiedIcon: {
      marginLeft: 8,
    },
    verifyButton: {
      borderColor: COLORS.error,
      borderRadius: 8,
      borderWidth: 1,
      color: COLORS.error,
      fontFamily: 'Uto-Medium',
      paddingBottom: 2,
      paddingHorizontal: 6,
      paddingTop: 4,
    },
  });
